// 
// Copyright (C) 2009 Nortel., certain elements licensed under a Contributor Agreement.  
// Contributors retain copyright to elements licensed under a Contributor Agreement.
// Licensed to the User under the LGPL license.
// 
// $$
//////////////////////////////////////////////////////////////////////////////
#ifndef _PAGINGALERT_H_
#define _PAGINGALERT_H_

// SYSTEM INCLUDES
// APPLICATION INCLUDES
#include <sipxproxy/AuthPlugin.h>

// DEFINES
// CONSTANTS
// TYPEDEFS
// FORWARD DECLARATIONS

extern "C" AuthPlugin* getAuthPlugin(const UtlString& name);

/**
 * The purpose of this AuthPlugin is to handle Alert-Info generated by freeswitch 
 * for paging and auto-answer. Freeswitch encloses the value of Alert-Info with <>
 * which is not recognize by polycom phones. 
 *
 * To fix this, Freeswitch will create a custom header X-Alert-Info for paging and
 * auto answer. This plugin will then replace with X-Alert-Info with actual Alert-Info
 * header which follows polycom (and other phones) syntax and format
 **/
class PagingAlert : public AuthPlugin
{
  public:

   /// destructor
   virtual ~PagingAlert();

   virtual
      AuthResult authorizeAndModify(const UtlString& id,    /**< The authenticated identity of the
                                                             *   request originator, if any (the null
                                                             *   string if not).
                                                             *   This is in the form of a SIP uri
                                                             *   identity value as used in the
                                                             *   credentials database (user@domain)
                                                             *   without the scheme or any parameters.
                                                             */
                                    const Url&  requestUri, ///< parsed target Uri
                                    RouteState& routeState, ///< the state for this request.  
                                    const UtlString& method,///< the request method
                                    AuthResult  priorResult,///< results from earlier plugins.
                                    SipMessage& request,    ///< see AuthPlugin regarding modifying
                                    bool bSpiralingRequest, ///< request spiraling indication 
                                    UtlString&  reason      ///< rejection reason
                                    );
   /**<
    *   The PagingAlert plug-in always returns AuthResult::CONTINUE
    */

   /// Read (or re-read) the authorization rules.
   virtual void readConfig( OsConfigDb& configDb /**< a subhash of the individual configuration
                                                  * parameters for this instance of this plugin. */
                           );
   /**<
    * @note
    * The parent service may call the readConfig method at any time to
    * indicate that the configuration may have changed.  The plugin
    * should reinitialize itself based on the configuration that exists when
    * this is called.  The fact that it is a subhash means that whatever prefix
    * is used to identify the plugin (see PluginHooks) has been removed (see the
    * examples in PluginHooks::readConfig).
    */

   virtual void announceAssociatedSipRouter( SipRouter* sipRouter );
   
  private:
   friend AuthPlugin* getAuthPlugin(const UtlString& name);

   /// Replaces Freeswitch X-Alert-Info headers supporting uncompliant Alert-Info Header
   /// for polycom phones use in paging and auto-answer.
   bool replaceXAlertInfo( SipMessage& request );
   
   /// Constructor - private so that only the factory can call it.
   PagingAlert(const UtlString& instanceName ///< the configured name for this plugin instance
                    );

   SipRouter* mpSipRouter; ///< stores pointer to owning SipRouter.

// @cond INCLUDENOCOPY
   
   /// There is no copy constructor.
   PagingAlert(const PagingAlert& nocopyconstructor);

   /// There is no assignment operator.
   PagingAlert& operator=(const PagingAlert& noassignmentoperator);
// @endcond INCLUDENOCOPY
};

#endif // _PAGINGALERT_H_
